name: Update gist with WakaTime Weekly development breakdown
on:
  schedule:
    - cron: "40 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update Weekly development
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 0cbf797d992465613ec8528a0e37ffcf
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
